export var words = [
    {"id": 1, "word": "abbreviate"},
    {"id": 2, "word": "bamboozled"},
    {"id": 3, "word": "calculator"},
    {"id": 4, "word": "disrespect"},
    {"id": 5, "word": "extraction"},
    {"id": 6, "word": "foundation"},
    {"id": 7, "word": "galvanized"},
    {"id": 8, "word": "hysterical"},
    {"id": 9, "word": "idiocratic"},
    {"id": 10, "word": "journalism"},
    {"id": 11, "word": "keelhauled"},
    {"id": 12, "word": "locomotion"},
    {"id": 13, "word": "minimalist"},
    {"id": 14, "word": "neutrality"},
    {"id": 15, "word": "opalescent"},
    {"id": 16, "word": "psilocybin"},
    {"id": 17, "word": "quaternion"},
    {"id": 18, "word": "ridiculous"},
    {"id": 19, "word": "sabbatical"},
    {"id": 20, "word": "turnbuckle"},
    {"id": 21, "word": "ultimately"},
    {"id": 22, "word": "voluptuous"},
    {"id": 23, "word": "wheatgrass"},
    {"id": 24, "word": "xenobiotic"},
    {"id": 25, "word": "yardmaster"},
    {"id": 26, "word": "zettabytes"}
  ]

  